### ISSUE TITLE
Blank page with self-signed HTTPS certificates

### ISSUE THREAD

**Issue by jens-duttke** [SupernaviX/LeiaWebXR#3]
As I wrote in #2 I'm developing a website. I'm doing that using a local dev environment, and to be able to use HTTPS features I have to use a self-signed certificate.
In Chrome I get the warning "NET::ERR_CERT_AUTHORITY_INVALID", but as I know the risk I can open my local website.

If I now share this website with your app, I just get a blank screen, and I'm unable to "Continue" to my "unsafe" page.

You can also test that here, which is using a self-signed certificate:
https://self-signed.badssl.com/

**Comment by jens-duttke** [comment]
I've just played around and after adding
```
import android.webkit.SslErrorHandler
import android.net.http.SslError
```
here:
https://github.com/SupernaviX/LeiaWebXR/blob/974b7a1b6b4bff9ac62677b3aedbc1a80dccbd69/app/src/main/java/com/simongellis/leia/webxr/MainActivity.kt#L14

and
```
override fun onReceivedSslError(view: WebView?, handler: SslErrorHandler, error: SslError?) {
    handler.proceed()
}
```
here:
https://github.com/SupernaviX/LeiaWebXR/blob/974b7a1b6b4bff9ac62677b3aedbc1a80dccbd69/app/src/main/java/com/simongellis/leia/webxr/MainActivity.kt#L50

it's working.

I know, ignoring certificate issues is bad - I'm sure an Android expert is able to show a dialog asking the user if he want to cancel or proceed.

**Comment by SupernaviX** [comment]
I added a prompt specifically to allow self-signed certs (after warning the user). It worked on the link you send, does it work on your local dev environment as well?

**Comment by jens-duttke** [comment]
That's perfect. Thanks!
