### ISSUE TITLE
Enable more browser features

### ISSUE THREAD

**Issue by jens-duttke** [SupernaviX/LeiaWebXR#5]
To have a better app-like feeling it would be great if some more settings (like the usage of the `localStorage`) could be enabled.

I played around with the options and replaced this line:
https://github.com/SupernaviX/LeiaWebXR/blob/d45b39dc9d51a5df7d916fc74e0558ea55e8f59e/app/src/main/java/com/simongellis/leia/webxr/MainActivity.kt#L54

by
```java
with(webView.settings) {
	javaScriptEnabled = true
	allowFileAccess = true
	allowContentAccess = true
	databaseEnabled = true
	domStorageEnabled = true
	javaScriptCanOpenWindowsAutomatically = true
	mediaPlaybackRequiresUserGesture = false
}
```

These options seems to be useful to me, what do you think?

**Comment by SupernaviX** [comment]
Those mostly sound useful and I turned most of them on. The only one I didn't was `javaScriptCanOpenWindowsAutomatically`, because
1. opening windows with XR mode active would probably break it
2. couldn't think of a reason it'd be helpful

**Comment by jens-duttke** [comment]
Perfect, thank you!
